### ISSUE TITLE
在安装模块wechat_mall时遇到csv文件处理错误的问题

### ISSUE THREAD

**Issue by Mocha-L** [elfgzp/wechat_mall#2]
你好
我在使用你提供的代码，安装wechat_mall模块时，提示报错如下，请问你有什么解决办法吗？

>  File "D:\code\python Proj\GOdoo10\source\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "D:\code\python Proj\GOdoo10\source\odoo\tools\convert.py", line 845, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "D:\code\python Proj\GOdoo10\source\odoo\tools\convert.py", line 901, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading wechat_mall failed: file wechat_mall\security/ir.model.access.csv could not be processed:
 \u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechatmall_config'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_banner'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_category'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_city'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_district'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property_child'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property_child_price'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_logistics'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_province'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_subshop'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_transportation'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_district_transportation'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_access_token'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_user'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_address'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_order'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_order_goods'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_shipper'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_payment'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_ir_attachment'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_config'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_banner'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_category'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_city'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_district'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property_child'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_goods_property_child_price'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_logistics'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_province'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_subshop'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_transportation'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_district_transportation'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_access_token'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_user'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_address'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_order'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_order_goods'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_shipper'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_payment'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_ir_attachment'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c

我是odoo新手，期待您的帮助，谢谢。

**Comment by elfgzp** [comment]
你可以尝试在所有模型描述前加模块前缀 例如model_ir_attachment - > base.model_ir_attachment

**Comment by Mocha-L** [comment]
@a741424975game 
我 用你的办法试了一下，其中model_ir_attachment经过修改确实不报错了，但是其他的修改后依然报错
我在想会不会是因为应用名包含_（下划线）导致的他找不到对应关系？部分报错信息如下：
你还有什么可以尝试的办法吗？

> File "D:\code\python Proj\GOdoo10\source\odoo\tools\convert.py", line 845, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "D:\code\python Proj\GOdoo10\source\odoo\tools\convert.py", line 901, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading wechat_mall failed: file wechat_mall\security/ir.model.access.csv could not be processed:
 \u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'base.model_wechat_mall_config'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_banner'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_category'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c
\u5728\u5b57\u6bb5'Object'\u4e2d\u6ca1\u627e\u5230\u5339\u914d\u7684\u8bb0\u5f55\u5916\u90e8id 'model_wechat_mall_city'
\u627e\u4e0d\u5230\u5b57\u6bb5 'Object' (model_id)\u6240\u9700\u7684\u503c

**Comment by elfgzp** [comment]
我觉得你需要在学习一下odoo  模块前缀不是随便加的你先参考一下官方的模块权限文件吧

**Comment by Mocha-L** [comment]
@a741424975game 
好的 我的确对odoo了解太少了 
issue先留一下 我解决了这个再来把解决方案贴出来 你再close
同时 也谢谢你~
^_^

**Comment by Mocha-L** [comment]
以上的问题解决了，通过删除数据库，重新初始化后重新安装成功了
期间还遇到了insert数据库的错误（sql报错），是因为sql中用了pgsql9.5的新特性，通过重新安装新版本PGSQL解决了。
希望作者可以在ReadMe中更新一下所使用环境。方便后来朋友使用。

**Comment by elfgzp** [comment]
好的哦 最近比较忙 感谢花时间研究这个项目~

**Comment by Flytutu** [comment]
在安装中也出现了一样的问题，为了方便其他人更好的解决问题，在这里也说一下，出现问题的原因是python的依赖库没有安装，程序中需要安装4个依赖包，在requirements.txt中有相关依赖。
